### ISSUE TITLE
Error upgrading .dat

### ISSUE THREAD

**Issue by nazcar4** [emphazer/GeoIP_convert-v2-v1#1] opened 2020-01-13 16:57 UTC
today when i create .dat script response:

ns:/usr/src/GeoIP_convert-v2-v1# ./geoip_convert-v2-v1.sh

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "./mmdb-convert-country.py", line 447, in <module>
    content = open(sys.argv[1], 'rb').read()
IOError: [Errno 2] No such file or directory: 'GeoLite2-Country_*/GeoLite2-Country.mmdb'
grep: geoip: No existe el fichero o el directorio
grep: geoip_country: No existe el fichero o el directorio
wrote 1-node trie with 0 networks (0 distinct labels) in 0 seconds
wrote 1-node trie with 0 networks (0 distinct labels) in 0 seconds
GeoIP Country Edition: IP Address not found
GeoIP Country Edition: NAME 20200113 Build

**Comment by RedXanadu** [comment] 2020-01-19 19:09
Hi,

The problem is that accessing the MaxMind GeoLite databases now requires a (freely available) licence key, as of 30 December 2019.

I've opened a pull request to add support to this script for specifying a licence key: #2 

For more details and info on how to sign up to get a licence key, see: [https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/)

Thanks.

**Comment by emphazer** [comment] 2021-10-27 19:01
fixed by @RedXanadu

**Closed as completed** 2021-10-27 19:00 UTC
